language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t systemsvs/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run systemsvs/react-test npm test -- --coverage

after_success:
  - docker build -t systemsvs/multi-client ./client
  - docker build -t systemsvs/multi-nginx ./nginx
  - docker build -t systemsvs/multi-server ./server
  - docker build -t systemsvs/multi-worker ./worker
  #login to the docker CLI
  #take those images and push them to docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push systemsvs/multi-client
  - docker push systemsvs/multi-nginx
  - docker push systemsvs/multi-server
  - docker push systemsvs/multi-worker
  


deploy:
  edge: true
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-129028259635
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: $AWS_SECRET_KEY  


